//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuiEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FuiEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogError {
            get {
                return ResourceManager.GetString("DialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open .fui. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogFailedToOpen {
            get {
                return ResourceManager.GetString("DialogFailedToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogInfo {
            get {
                return ResourceManager.GetString("DialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You&apos;ve not saved the .fui yet. Do you exit this application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogNotifySave {
            get {
                return ResourceManager.GetString("DialogNotifySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Fui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogOpenFui {
            get {
                return ResourceManager.GetString("DialogOpenFui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogReplaceImage {
            get {
                return ResourceManager.GetString("DialogReplaceImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saved Fui! ({0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogSavedFui {
            get {
                return ResourceManager.GetString("DialogSavedFui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Fui に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogSaveFui {
            get {
                return ResourceManager.GetString("DialogSaveFui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogSaveImage {
            get {
                return ResourceManager.GetString("DialogSaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select image first, please. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogSelectImage {
            get {
                return ResourceManager.GetString("DialogSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogWarning {
            get {
                return ResourceManager.GetString("DialogWarning", resourceCulture);
            }
        }
    }
}
